// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiwggXPtUAGNoyweoUyrfYRgv2fx2GrGw',
    appId: '1:988979923331:web:01192e3ea977b9cdf0ceb6',
    messagingSenderId: '988979923331',
    projectId: 'study-86d58',
    authDomain: 'study-86d58.firebaseapp.com',
    storageBucket: 'study-86d58.appspot.com',
    measurementId: 'G-7748LM21HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc3xQaZVaOu_GOjR-Azr3g5x2C-x1y9hQ',
    appId: '1:988979923331:android:eff4f48bedf7df87f0ceb6',
    messagingSenderId: '988979923331',
    projectId: 'study-86d58',
    storageBucket: 'study-86d58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWqIvIG5_NvW4WzJqExm-nm6bysJtkMzQ',
    appId: '1:988979923331:ios:233478b383575d7af0ceb6',
    messagingSenderId: '988979923331',
    projectId: 'study-86d58',
    storageBucket: 'study-86d58.appspot.com',
    iosBundleId: 'com.example.study',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWqIvIG5_NvW4WzJqExm-nm6bysJtkMzQ',
    appId: '1:988979923331:ios:233478b383575d7af0ceb6',
    messagingSenderId: '988979923331',
    projectId: 'study-86d58',
    storageBucket: 'study-86d58.appspot.com',
    iosBundleId: 'com.example.study',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiwggXPtUAGNoyweoUyrfYRgv2fx2GrGw',
    appId: '1:988979923331:web:7fea4f43e4ed1a5ef0ceb6',
    messagingSenderId: '988979923331',
    projectId: 'study-86d58',
    authDomain: 'study-86d58.firebaseapp.com',
    storageBucket: 'study-86d58.appspot.com',
    measurementId: 'G-SRXNRLX0TF',
  );
}
